name: Publish NuGet Package

on:
  push:
    branches:
      - main  # Monitor the main branch
  workflow_dispatch: # To trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Set the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests for Maskify.Core.Tests
        run: dotnet test ./Maskfy.Core.Tests/Maskify.Core.Tests.csproj --no-restore --no-build

      - name: Pack project
        run: dotnet pack --configuration Release --no-build -o ./nupkg

      - name: Push NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
